### ISSUE TITLE
org.bukkit.craftbukkit.v1_16_R2.entity.CraftVillager cannot be cast to org.bukkit.entity.Player

### ISSUE THREAD

**Issue by rekbx** [APJifengc/Bingo#6]
When trying to interact with a villager, the server throws this error and may shutdown. 
Also some other interactions cannot be cast.
Server - paper#240 1.16.3
```
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R2.entity.CraftVillager cannot be cast to org.bukkit.entity.Player
	at me.pzdrs.bingo.listeners.EventPlayerInteractEntity.onInteract(EventPlayerInteractEntity.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-240]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2093) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by milkory** [comment]
Uh... Are you sure that you are using the Bingo plugin we made? You can see that the package name in the log is `me.pzdrs.bingo` rather than `github.apjifengc.bingo`.

~~Solution: use our plugin now~~

**Comment by milkory** [comment]
The issue expired because it took too long to reply.
